# Generated by Django 5.1.2 on 2024-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_chat_id',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name='телеграмм чат id'),
        ),
    ]
