# Generated by Django 5.1.2 on 2024-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время, до которого выполнить привычку')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('period_in_days', models.IntegerField(default=1, verbose_name='периодичность выполнения в днях')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_action_in_sec', models.IntegerField(verbose_name='время на выполнение')),
            ],
        ),
    ]
