# Generated by Django 5.1.2 on 2024-12-01 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_completedhabit_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedhabit',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 19, 5, 12, 23076), verbose_name='время завершения'),
        ),
    ]
