# Generated by Django 5.1.2 on 2024-12-11 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_completedhabit_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedhabit',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 8, 7, 50, 487780), verbose_name='время завершения'),
        ),
    ]
